### ISSUE TITLE
About Net of stage

### ISSUE THREAD

**Issue by dushide** [yangyan92/Deep-ADMM-Net#2]
Dear Teacher Yang:
Thank you for your excellent research work, 
I have a question to ask about different stages in './net/network_20'.
How do I generate different number of stages, such as 12 stages :'net-stage12.mat'.
In other words, I want to generate something different from what you provide ‘net-stage5.mat, net-stage14.mat, net-stage15.mat’ under the file you provided .
Looking forward to your reply.
Sincerely

**Comment by yangyan92** [comment]
You can tune network parameters in config.m

**Comment by dushide** [comment]
Thank you for your reply. That solved my problem pretty well
